# Generated by Django 6.0.4 on 2026-04-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='locked_balance',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive for credits, negative for debits', max_digits=12),
        ),
    ]
