# Generated by Django 6.0.4 on 2026-04-11 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NjangiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cycle_length', models.IntegerField(help_text='Number of members/cycles')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_order', models.IntegerField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.njangigroup')),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False)),
                ('cycle_number', models.IntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_amount', models.DecimalField(decimal_places=2, help_text='60% of total', max_digits=12)),
                ('locked_amount', models.DecimalField(decimal_places=2, help_text='40% of total', max_digits=12)),
                ('date_disbursed', models.DateTimeField(auto_now_add=True)),
                ('cycle_number', models.IntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='groups.membership')),
            ],
        ),
    ]
