# Generated by Django 6.0.4 on 2026-04-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='njangigroup',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
