# Generated by Django 6.0.4 on 2026-04-11 20:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_njangigroup_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='njangigroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='groups.njangigroup')),
            ],
        ),
    ]
