# Generated by Django 6.0.4 on 2026-04-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_njangigroup_admin_grouppool'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'Mobile Money'), ('BANK', 'Bank Transfer'), ('WALLET', 'Internal Wallet')], default='WALLET', max_length=10),
        ),
    ]
