# Generated by Django 6.0.4 on 2026-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_contribution_is_verified_contribution_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cycle_start_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_NEXT_CYCLE', 'Pending Next Cycle'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='njangigroup',
            name='current_cycle_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='njangigroup',
            name='description',
            field=models.TextField(blank=True, help_text='About this Njangi'),
        ),
        migrations.AddField(
            model_name='njangigroup',
            name='rules',
            field=models.TextField(blank=True, help_text='Group rules and conduct'),
        ),
    ]
