sonar.projectKey=Njangi
sonar.projectName=Digital Tontine / Njangi
sonar.sources=.
sonar.language=py
sonar.python.version=3.14.4
sonar.host.url=http://127.0.0.1:8001
sonar.login=sqa_9af01b8dbd1d678543b57b9d2582286413dd1c9e
