# Generated by Django 6.0.4 on 2026-05-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_full_name_user_is_verified_user_referral_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
