sonar.projectKey=Njangi-Frontend
sonar.projectName=Digital Tontine / Njangi Frontend Testing
sonar.sources=.
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.host.url=http://127.0.0.1:8082
sonar.login=sqa_8fe1a40a1e412bb058e671f28029f05ae0a74f3e
